config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => {registrations: 'registrations'}
  get 'pages/about'

  root to: 'pages#index'

  get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def contact
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
 private
	 def sign_up_params
		 params.require(:user).permit(
			 :email,
			 :password,
			 :password_confirmation,
			 :username,
			 :firstname,
			 :lastname
		 )
	 end
	 def account_update_params
		 params.require(:user).permit(
			 :email,
			 :password,
			 :password_confirmation,
			 :current_password,
			 :username,
			 :firstname,
			 :lastname
		 )
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_busca.html.erb
<div class="search-box-wrapper">
	<input type="text" class="search-box-input" placeholder="Buscar...">
	<button class="search-box-button">
		<span class="glyphicon glyphicon-search" aria-hidden="true"></span>
	</button>
	<button class="document-box-button">Pesquisar com documento</button> 
</div>

app/views/layouts/_foot.html.erb
</footer>
<footer class="footer-distributed">
	<div class="footer-right">
		<div class="footer-icons">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-github"></i></a>
		</div>
	</div>
	<div class="footer-left">
		<p class="footer-links">
			·
			<a class="page-scroll" href="#portfolio">Contact Us</a>
			·
			<a class="page-scroll" href="#services">About Us</a>
			·
		</p>
		<p> </p>
	</div>
</footer>
<!--
<footer class="footer-distributed">
	<div class="footer-left">
		<h3>Company<span>logo</span></h3>
		<p class="footer-links">
			<a href="#">Home</a>
			·
			<a href="#">Blog</a>
			·
			<a href="#">Pricing</a>
			·
			<a href="#">About</a>
			·
			<a href="#">Faq</a>
			·
			<a href="#">Contact</a>
		</p>
		<p class="footer-company-name">Company Name &copy; 2015</p>
		<div class="footer-icons">
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-github"></i></a>
		</div>
	</div>
	<div class="footer-right">
	<p>Contact Us</p>
		<form action="#" method="post">
		<input type="text" name="email" placeholder="Email" />
		<textarea name="message" placeholder="Message"></textarea>
		<button>Send</button>
	</form>
	</div>
</footer>
!-->

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <%= link_to 'MatchUp', root_path, class: 'navbar-brand' %>
	    </div>
	      <ul class="nav navbar-nav navbar-right">
  	          <% if not current_user %>
	          		<li><%= link_to 'Registrar-se', new_user_registration_path %></li>
	          <% end %>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-th" aria-hidden="true"></span></a>
	          <ul class="dropdown-menu">
	          	<li><%= link_to 'Gerenciar Coleções'.html_safe, edit_user_registration_path %></li>
	          	<% if current_user %>		            
		            <li role="separator" class="divider"></li>
		            <li><%= link_to 'Editar Perfil', edit_user_registration_path %></li>
		            <li role="separator" class="divider"></li>
		            <li><%= link_to 'Sair'.html_safe, destroy_user_session_path, method: :delete %></li>
		        <% else %>
		            <li role="separator" class="divider"></li>
		            <li><%= link_to "Registrar-se", new_user_registration_path %></li>
		        <% end %>
		        <li role="separator" class="divider"></li>
	            <li><%= link_to "Contate-nos", pages_contact_path %></li>
	            <li><%= link_to "Sobre MatchUp", pages_about_path %></li>
	          </ul>
	        </li>
            <% if current_user %>
                <li><%= link_to '<span class="glyphicon glyphicon-log-out" aria-hidden="true"> Sair</span>'.html_safe, destroy_user_session_path, method: :delete %></li>
            <% else %>
                <li><%= link_to '<span class="glyphicon glyphicon-log-in" aria-hidden="true"> Login</span>'.html_safe, new_user_session_path %></li>
            <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchUp - Encontre os documentos que precisa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= bootstrap_flash %>
    <div class='container'>
      <%= yield %>
    </div>
    <%= render 'layouts/foot' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <h2>About Grayscale</h2>
        <p>Grayscale is a free Bootstrap 3 theme created by Start Bootstrap. It can be yours right now, simply download the template on <a href="http://startbootstrap.com/template-overviews/grayscale/">the preview page</a>. The theme is open source, and you can use it for any purpose, personal or commercial.</p>
        <p>This theme features stock photos by <a href="http://gratisography.com/">Gratisography</a> along with a custom Google Maps skin courtesy of <a href="http://snazzymaps.com/">Snazzy Maps</a>.</p>
        <p>Grayscale includes full HTML, CSS, and custom JavaScript files along with LESS files for easy customization.</p>
    </div>
</div>

app/views/pages/contact.html.erb
<!-- Page Heading/Breadcrumbs -->
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Contate-nos
            <small>Será um prazer atendê-los</small>
        </h1>
    </div>
</div>
<!-- /.row -->

<!-- Content Row -->
<div class="row">
    <!-- Map Column -->
    <div class="col-md-8">
        <!-- Embedded Google Map -->
        <iframe width="100%" height="400px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?hl=en&amp;ie=UTF8&amp;ll=37.0625,-95.677068&amp;spn=56.506174,79.013672&amp;t=m&amp;z=4&amp;output=embed"></iframe>
        AIzaSyDCJWcY4-9-LNmO1ThGatBEVXpXRBhHq3k
        ChIJ5TWJVVr4owARsGzXxl9Z-Ng
    </div>
    <!-- Contact Details Column -->
    <div class="col-md-4">
        <h3>Detalhes de contato</h3>
        <p>
            Rua Antônio José Ramos, 101, Bauxita<br>Ouro Preto-MG, Brasil<br>
        </p>
        <p><i class="fa fa-phone"></i> 
            <abbr title="Phone">Telefone</abbr>: (31)98933-9423</p>
        <p><i class="fa fa-envelope-o"></i> 
            <abbr title="Email">E</abbr>: <a href="mailto:luizjaneiro007@hotmail.com">luizjaneiro007@hotmail.com</a>
        </p>
        <p><i class="fa fa-clock-o"></i> 
            <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
        <ul class="list-unstyled list-inline list-social-icons">
            <li>
                <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
            </li>
            <li>
                <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
            </li>
        </ul>
    </div>
</div>
<!-- /.row -->

<!-- Contact Form -->
<!-- In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<div class="row">
    <div class="col-md-8">
        <h3>Send us a Message</h3>
        <form name="sentMessage" id="contactForm" novalidate>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Full Name:</label>
                    <input type="text" class="form-control" id="name" required data-validation-required-message="Please enter your name.">
                    <p class="help-block"></p>
                </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Phone Number:</label>
                    <input type="tel" class="form-control" id="phone" required data-validation-required-message="Please enter your phone number.">
                </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Email Address:</label>
                    <input type="email" class="form-control" id="email" required data-validation-required-message="Please enter your email address.">
                </div>
            </div>
            <div class="control-group form-group">
                <div class="controls">
                    <label>Message:</label>
                    <textarea rows="10" cols="100" class="form-control" id="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
                </div>
            </div>
            <div id="success"></div>
            <!-- For success/fail messages -->
            <button type="submit" class="btn btn-primary">Send Message</button>
        </form>
    </div>

</div>
<!-- /.row -->

<hr>

<!-- Footer -->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </div>
</footer>

</div>

<!-- jQuery -->
<script src="js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="js/bootstrap.min.js"></script>

<!-- Contact Form JavaScript -->
<!-- Do not edit these files! In order to set the email address and subject line for the contact form go to the bin/contact_me.php file. -->
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

app/views/pages/index.html.erb
<%= render 'layouts/busca' %>